### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by kachick** [kachick/dotfiles#527]
- [ ] Git Repository - forgejo - https://github.com/kachick/dotfiles/pull/850
- [ ] Shell History Backup - atuin? - https://github.com/kachick/dotfiles/issues/173
- [ ] VPN - tailscale - https://github.com/kachick/dotfiles/issues/573
- [ ] Data Backup - https://github.com/kachick/dotfiles/issues/709
- [ ] Nix Binary Cache - https://github.com/kachick/dotfiles/issues/754
- [ ] Secret Manager - vaultwarden? - https://github.com/kachick/dotfiles/issues/262
- [ ] RSS feed generator - https://github.com/kachick/times_kachick/issues/242, https://github.com/kachick/times_kachick/issues/304#issuecomment-2320756024, https://docs.rsshub.app/guide/instances
- [ ] NAS - Samba? https://nixos.wiki/wiki/Seafile?
- [ ] SSH - https://github.com/kachick/dotfiles/issues/802
- [ ] Chat - https://github.com/mattermost/mattermost
- [ ] Kubernetes - https://github.com/kachick/dotfiles/issues/915

ref: https://github.com/awesome-selfhosted/awesome-selfhosted

**Comment by kachick** [comment]
The scope is much large and might be changed the method since introducing https://github.com/kachick/dotfiles/pull/898
